name: cuid
description: cuid is a library for generating unique collision-resistant IDs optimized for horizontal scaling and performance
version: 0.1.2
author: Levi Cook <levicook@gmail.com>
homepage: https://github.com/levicook/cuid

dev_dependencies:
  test: ^1.6.4

environment:
  sdk: ">=2.17.0 <3.0.0"
